name: npm publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 11
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Check type
        run: pnpm run type:check
      - name: Build
        run: pnpm run build
      - name: Publish npm (dry run)
        run: pnpm publish --dry-run --no-git-checks
