name: npm publish

on:
  push:
    tags:
      - '*'

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          version: 7
      - name: Install
        run: pnpm install
      - name: Check type
        run: pnpm run type:check
      - name: Build
        run: pnpm run build
      - uses: JS-DevTools/npm-publish@v1
        name: Publish npm
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
